[project]
name = "boilerplate-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]==0.124.0",
]

[dependency-groups]
dev = [
    "pyrefly==0.45.1",
    "ruff==0.14.8",
]
